# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import taskgrid_pb2 as taskgrid__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in taskgrid_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class NamingServiceStub(object):
    """──────────────────────────────────────────────────────────────────────────────
    Services
    ──────────────────────────────────────────────────────────────────────────────

    NamingService (Elena-kompatibel) — implementiert von Xplosy
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterWorker = channel.unary_unary(
                '/taskgrid.NamingService/RegisterWorker',
                request_serializer=taskgrid__pb2.WorkerInfo.SerializeToString,
                response_deserializer=taskgrid__pb2.Ack.FromString,
                _registered_method=True)
        self.SendHeartbeat = channel.unary_unary(
                '/taskgrid.NamingService/SendHeartbeat',
                request_serializer=taskgrid__pb2.HeartbeatRequest.SerializeToString,
                response_deserializer=taskgrid__pb2.Ack.FromString,
                _registered_method=True)
        self.DeregisterWorker = channel.unary_unary(
                '/taskgrid.NamingService/DeregisterWorker',
                request_serializer=taskgrid__pb2.WorkerInfo.SerializeToString,
                response_deserializer=taskgrid__pb2.Ack.FromString,
                _registered_method=True)
        self.LookupWorker = channel.unary_unary(
                '/taskgrid.NamingService/LookupWorker',
                request_serializer=taskgrid__pb2.LookupRequest.SerializeToString,
                response_deserializer=taskgrid__pb2.LookupResponse.FromString,
                _registered_method=True)


class NamingServiceServicer(object):
    """──────────────────────────────────────────────────────────────────────────────
    Services
    ──────────────────────────────────────────────────────────────────────────────

    NamingService (Elena-kompatibel) — implementiert von Xplosy
    """

    def RegisterWorker(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendHeartbeat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeregisterWorker(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LookupWorker(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NamingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterWorker': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterWorker,
                    request_deserializer=taskgrid__pb2.WorkerInfo.FromString,
                    response_serializer=taskgrid__pb2.Ack.SerializeToString,
            ),
            'SendHeartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.SendHeartbeat,
                    request_deserializer=taskgrid__pb2.HeartbeatRequest.FromString,
                    response_serializer=taskgrid__pb2.Ack.SerializeToString,
            ),
            'DeregisterWorker': grpc.unary_unary_rpc_method_handler(
                    servicer.DeregisterWorker,
                    request_deserializer=taskgrid__pb2.WorkerInfo.FromString,
                    response_serializer=taskgrid__pb2.Ack.SerializeToString,
            ),
            'LookupWorker': grpc.unary_unary_rpc_method_handler(
                    servicer.LookupWorker,
                    request_deserializer=taskgrid__pb2.LookupRequest.FromString,
                    response_serializer=taskgrid__pb2.LookupResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'taskgrid.NamingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('taskgrid.NamingService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class NamingService(object):
    """──────────────────────────────────────────────────────────────────────────────
    Services
    ──────────────────────────────────────────────────────────────────────────────

    NamingService (Elena-kompatibel) — implementiert von Xplosy
    """

    @staticmethod
    def RegisterWorker(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/taskgrid.NamingService/RegisterWorker',
            taskgrid__pb2.WorkerInfo.SerializeToString,
            taskgrid__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendHeartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/taskgrid.NamingService/SendHeartbeat',
            taskgrid__pb2.HeartbeatRequest.SerializeToString,
            taskgrid__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeregisterWorker(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/taskgrid.NamingService/DeregisterWorker',
            taskgrid__pb2.WorkerInfo.SerializeToString,
            taskgrid__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LookupWorker(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/taskgrid.NamingService/LookupWorker',
            taskgrid__pb2.LookupRequest.SerializeToString,
            taskgrid__pb2.LookupResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class DispatcherServiceStub(object):
    """DispatcherService — Client → Dispatcher + Worker → Dispatcher
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PostTask = channel.unary_unary(
                '/taskgrid.DispatcherService/PostTask',
                request_serializer=taskgrid__pb2.PostTaskRequest.SerializeToString,
                response_deserializer=taskgrid__pb2.TaskResponse.FromString,
                _registered_method=True)
        self.GetResult = channel.unary_unary(
                '/taskgrid.DispatcherService/GetResult',
                request_serializer=taskgrid__pb2.GetResultRequest.SerializeToString,
                response_deserializer=taskgrid__pb2.ResultResponse.FromString,
                _registered_method=True)
        self.GetStatus = channel.unary_unary(
                '/taskgrid.DispatcherService/GetStatus',
                request_serializer=taskgrid__pb2.StatusRequest.SerializeToString,
                response_deserializer=taskgrid__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.ReturnResult = channel.unary_unary(
                '/taskgrid.DispatcherService/ReturnResult',
                request_serializer=taskgrid__pb2.ResultRequest.SerializeToString,
                response_deserializer=taskgrid__pb2.Ack.FromString,
                _registered_method=True)


class DispatcherServiceServicer(object):
    """DispatcherService — Client → Dispatcher + Worker → Dispatcher
    """

    def PostTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetResult(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReturnResult(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DispatcherServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PostTask': grpc.unary_unary_rpc_method_handler(
                    servicer.PostTask,
                    request_deserializer=taskgrid__pb2.PostTaskRequest.FromString,
                    response_serializer=taskgrid__pb2.TaskResponse.SerializeToString,
            ),
            'GetResult': grpc.unary_unary_rpc_method_handler(
                    servicer.GetResult,
                    request_deserializer=taskgrid__pb2.GetResultRequest.FromString,
                    response_serializer=taskgrid__pb2.ResultResponse.SerializeToString,
            ),
            'GetStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStatus,
                    request_deserializer=taskgrid__pb2.StatusRequest.FromString,
                    response_serializer=taskgrid__pb2.StatusResponse.SerializeToString,
            ),
            'ReturnResult': grpc.unary_unary_rpc_method_handler(
                    servicer.ReturnResult,
                    request_deserializer=taskgrid__pb2.ResultRequest.FromString,
                    response_serializer=taskgrid__pb2.Ack.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'taskgrid.DispatcherService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('taskgrid.DispatcherService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DispatcherService(object):
    """DispatcherService — Client → Dispatcher + Worker → Dispatcher
    """

    @staticmethod
    def PostTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/taskgrid.DispatcherService/PostTask',
            taskgrid__pb2.PostTaskRequest.SerializeToString,
            taskgrid__pb2.TaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetResult(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/taskgrid.DispatcherService/GetResult',
            taskgrid__pb2.GetResultRequest.SerializeToString,
            taskgrid__pb2.ResultResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/taskgrid.DispatcherService/GetStatus',
            taskgrid__pb2.StatusRequest.SerializeToString,
            taskgrid__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReturnResult(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/taskgrid.DispatcherService/ReturnResult',
            taskgrid__pb2.ResultRequest.SerializeToString,
            taskgrid__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class WorkerServiceStub(object):
    """WorkerService (Elena-kompatibel) — implementiert von Worker
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ExecuteTask = channel.unary_unary(
                '/taskgrid.WorkerService/ExecuteTask',
                request_serializer=taskgrid__pb2.TaskRequest.SerializeToString,
                response_deserializer=taskgrid__pb2.TaskResponse.FromString,
                _registered_method=True)


class WorkerServiceServicer(object):
    """WorkerService (Elena-kompatibel) — implementiert von Worker
    """

    def ExecuteTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WorkerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ExecuteTask': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecuteTask,
                    request_deserializer=taskgrid__pb2.TaskRequest.FromString,
                    response_serializer=taskgrid__pb2.TaskResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'taskgrid.WorkerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('taskgrid.WorkerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class WorkerService(object):
    """WorkerService (Elena-kompatibel) — implementiert von Worker
    """

    @staticmethod
    def ExecuteTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/taskgrid.WorkerService/ExecuteTask',
            taskgrid__pb2.TaskRequest.SerializeToString,
            taskgrid__pb2.TaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
