# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import taskgrid_pb2 as taskgrid__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in taskgrid_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DispatcherServiceStub(object):
    """──────────────────────────────────────────────
    DispatcherService  (Client → Dispatcher)
    ──────────────────────────────────────────────

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PostTask = channel.unary_unary(
                '/taskgrid.DispatcherService/PostTask',
                request_serializer=taskgrid__pb2.TaskRequest.SerializeToString,
                response_deserializer=taskgrid__pb2.TaskResponse.FromString,
                _registered_method=True)
        self.GetResult = channel.unary_unary(
                '/taskgrid.DispatcherService/GetResult',
                request_serializer=taskgrid__pb2.ResultRequest.SerializeToString,
                response_deserializer=taskgrid__pb2.ResultResponse.FromString,
                _registered_method=True)
        self.GetStatus = channel.unary_unary(
                '/taskgrid.DispatcherService/GetStatus',
                request_serializer=taskgrid__pb2.StatusRequest.SerializeToString,
                response_deserializer=taskgrid__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.ReceiveResult = channel.unary_unary(
                '/taskgrid.DispatcherService/ReceiveResult',
                request_serializer=taskgrid__pb2.ResultReturn.SerializeToString,
                response_deserializer=taskgrid__pb2.Ack.FromString,
                _registered_method=True)


class DispatcherServiceServicer(object):
    """──────────────────────────────────────────────
    DispatcherService  (Client → Dispatcher)
    ──────────────────────────────────────────────

    """

    def PostTask(self, request, context):
        """POST_TASK: Client gibt Task ab, erhält task_id zurück
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetResult(self, request, context):
        """GET_RESULT: Client fragt Ergebnis ab
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStatus(self, request, context):
        """GET_STATUS: Monitoring fragt Systemzustand ab
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReceiveResult(self, request, context):
        """RESULT_RETURN: Worker liefert fertiges Ergebnis zurück
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DispatcherServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PostTask': grpc.unary_unary_rpc_method_handler(
                    servicer.PostTask,
                    request_deserializer=taskgrid__pb2.TaskRequest.FromString,
                    response_serializer=taskgrid__pb2.TaskResponse.SerializeToString,
            ),
            'GetResult': grpc.unary_unary_rpc_method_handler(
                    servicer.GetResult,
                    request_deserializer=taskgrid__pb2.ResultRequest.FromString,
                    response_serializer=taskgrid__pb2.ResultResponse.SerializeToString,
            ),
            'GetStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStatus,
                    request_deserializer=taskgrid__pb2.StatusRequest.FromString,
                    response_serializer=taskgrid__pb2.StatusResponse.SerializeToString,
            ),
            'ReceiveResult': grpc.unary_unary_rpc_method_handler(
                    servicer.ReceiveResult,
                    request_deserializer=taskgrid__pb2.ResultReturn.FromString,
                    response_serializer=taskgrid__pb2.Ack.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'taskgrid.DispatcherService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('taskgrid.DispatcherService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DispatcherService(object):
    """──────────────────────────────────────────────
    DispatcherService  (Client → Dispatcher)
    ──────────────────────────────────────────────

    """

    @staticmethod
    def PostTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/taskgrid.DispatcherService/PostTask',
            taskgrid__pb2.TaskRequest.SerializeToString,
            taskgrid__pb2.TaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetResult(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/taskgrid.DispatcherService/GetResult',
            taskgrid__pb2.ResultRequest.SerializeToString,
            taskgrid__pb2.ResultResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/taskgrid.DispatcherService/GetStatus',
            taskgrid__pb2.StatusRequest.SerializeToString,
            taskgrid__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReceiveResult(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/taskgrid.DispatcherService/ReceiveResult',
            taskgrid__pb2.ResultReturn.SerializeToString,
            taskgrid__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class NamensdienstServiceStub(object):
    """──────────────────────────────────────────────
    NamensdienstService  (Worker/Dispatcher → Namensdienst)
    ──────────────────────────────────────────────

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterWorker = channel.unary_unary(
                '/taskgrid.NamensdienstService/RegisterWorker',
                request_serializer=taskgrid__pb2.RegisterRequest.SerializeToString,
                response_deserializer=taskgrid__pb2.Ack.FromString,
                _registered_method=True)
        self.Heartbeat = channel.unary_unary(
                '/taskgrid.NamensdienstService/Heartbeat',
                request_serializer=taskgrid__pb2.HeartbeatRequest.SerializeToString,
                response_deserializer=taskgrid__pb2.Ack.FromString,
                _registered_method=True)
        self.LookupWorker = channel.unary_unary(
                '/taskgrid.NamensdienstService/LookupWorker',
                request_serializer=taskgrid__pb2.LookupRequest.SerializeToString,
                response_deserializer=taskgrid__pb2.LookupResponse.FromString,
                _registered_method=True)
        self.DeregisterWorker = channel.unary_unary(
                '/taskgrid.NamensdienstService/DeregisterWorker',
                request_serializer=taskgrid__pb2.DeregisterRequest.SerializeToString,
                response_deserializer=taskgrid__pb2.Ack.FromString,
                _registered_method=True)


class NamensdienstServiceServicer(object):
    """──────────────────────────────────────────────
    NamensdienstService  (Worker/Dispatcher → Namensdienst)
    ──────────────────────────────────────────────

    """

    def RegisterWorker(self, request, context):
        """REGISTER_WORKER: Worker meldet sich an
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Heartbeat(self, request, context):
        """HEARTBEAT: Worker sendet Lebenszeichen
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LookupWorker(self, request, context):
        """LOOKUP_WORKER: Dispatcher fragt passenden Worker für Tasktyp
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeregisterWorker(self, request, context):
        """DEREGISTER_WORKER: Worker meldet sich beim Shutdown ab
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NamensdienstServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterWorker': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterWorker,
                    request_deserializer=taskgrid__pb2.RegisterRequest.FromString,
                    response_serializer=taskgrid__pb2.Ack.SerializeToString,
            ),
            'Heartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.Heartbeat,
                    request_deserializer=taskgrid__pb2.HeartbeatRequest.FromString,
                    response_serializer=taskgrid__pb2.Ack.SerializeToString,
            ),
            'LookupWorker': grpc.unary_unary_rpc_method_handler(
                    servicer.LookupWorker,
                    request_deserializer=taskgrid__pb2.LookupRequest.FromString,
                    response_serializer=taskgrid__pb2.LookupResponse.SerializeToString,
            ),
            'DeregisterWorker': grpc.unary_unary_rpc_method_handler(
                    servicer.DeregisterWorker,
                    request_deserializer=taskgrid__pb2.DeregisterRequest.FromString,
                    response_serializer=taskgrid__pb2.Ack.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'taskgrid.NamensdienstService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('taskgrid.NamensdienstService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class NamensdienstService(object):
    """──────────────────────────────────────────────
    NamensdienstService  (Worker/Dispatcher → Namensdienst)
    ──────────────────────────────────────────────

    """

    @staticmethod
    def RegisterWorker(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/taskgrid.NamensdienstService/RegisterWorker',
            taskgrid__pb2.RegisterRequest.SerializeToString,
            taskgrid__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Heartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/taskgrid.NamensdienstService/Heartbeat',
            taskgrid__pb2.HeartbeatRequest.SerializeToString,
            taskgrid__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LookupWorker(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/taskgrid.NamensdienstService/LookupWorker',
            taskgrid__pb2.LookupRequest.SerializeToString,
            taskgrid__pb2.LookupResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeregisterWorker(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/taskgrid.NamensdienstService/DeregisterWorker',
            taskgrid__pb2.DeregisterRequest.SerializeToString,
            taskgrid__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class WorkerServiceStub(object):
    """──────────────────────────────────────────────
    WorkerService  (Dispatcher → Worker)
    ──────────────────────────────────────────────

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.DispatchTask = channel.unary_unary(
                '/taskgrid.WorkerService/DispatchTask',
                request_serializer=taskgrid__pb2.DispatchRequest.SerializeToString,
                response_deserializer=taskgrid__pb2.Ack.FromString,
                _registered_method=True)


class WorkerServiceServicer(object):
    """──────────────────────────────────────────────
    WorkerService  (Dispatcher → Worker)
    ──────────────────────────────────────────────

    """

    def DispatchTask(self, request, context):
        """Dispatcher weist Worker einen Task zu
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WorkerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'DispatchTask': grpc.unary_unary_rpc_method_handler(
                    servicer.DispatchTask,
                    request_deserializer=taskgrid__pb2.DispatchRequest.FromString,
                    response_serializer=taskgrid__pb2.Ack.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'taskgrid.WorkerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('taskgrid.WorkerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class WorkerService(object):
    """──────────────────────────────────────────────
    WorkerService  (Dispatcher → Worker)
    ──────────────────────────────────────────────

    """

    @staticmethod
    def DispatchTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/taskgrid.WorkerService/DispatchTask',
            taskgrid__pb2.DispatchRequest.SerializeToString,
            taskgrid__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
